#!/bin/sh
pushd `dirname $0`/result/bin>/dev/null; trap "popd>/dev/null" EXIT
Base=../share/arcan
Appls=$Base/appl
Scripts=$Base/scripts
Resources=$Base/resources
./arcan_sdl -t $Appls -T $Scripts -p $Resources console
