#!/bin/sh
Appls=`realpath $(dirname $0)`
echo $Appls
pushd `dirname $0`/result/bin>/dev/null; trap "popd>/dev/null" EXIT
Base=../share/arcan
Scripts=$Base/scripts
Resources=$Base/resources
./arcan_sdl -t $Appls -T $Scripts -p $Resources -f prio
